### ISSUE TITLE
Add brief description to "About" section

### ISSUE THREAD

**Issue by ksuchak1990** [eeyouol/covpol#24]
The "About" section for the repository should contain a brief description of the project to let people know what it is about.

**Comment by eeyouol** [comment]
hi @ksuchak1990, do you refer to the readme or wiki? I do not see another about page right now. Also I do think to be honest, it is fine if there is just the reference, and ideally link to the, published paper? which has all the descriptions in it?

**Comment by ksuchak1990** [comment]
The bit that I'm referring to is the red bit in the picture below. When people are browsing GitHub, this will be a 1-2 sentence blurb about the repo that they will see and could be handy increase traffic to the repo.

![Screenshot 2023-01-30 103219](https://user-images.githubusercontent.com/18059900/215453736-6a09256a-b93f-4a46-91f6-fd8889dfbd88.png)

**Comment by eeyouol** [comment]
thanks. done.
